let worldArr = [{ "en": "abort", "kr": "유산하다" },
{ "en": "about", "kr": "-에 대하여" },
{ "en": "above", "kr": "-보다 위에" },
{ "en": "abuse", "kr": "남용" },
{ "en": "acute", "kr": "날카로운" },
{ "en": "adapt", "kr": "적용시키다" },
{ "en": "admit", "kr": "받아들이다" },
{ "en": "adopt", "kr": "채용하다" },
{ "en": "adult", "kr": "성인" },
{ "en": "after", "kr": "후에" },
{ "en": "again", "kr": "다시" },
{ "en": "agent", "kr": "대리인" },
{ "en": "agree", "kr": "동의하다" },
{ "en": "ahead", "kr": "전방에" },
{ "en": "aisle", "kr": "측면복도" },
{ "en": "alert", "kr": "빈틈없는" },
{ "en": "alien", "kr": "외국의" },
{ "en": "alike", "kr": "비슷한" },
{ "en": "alive", "kr": "살아있는" },
{ "en": "allow", "kr": "허락하다" },
{ "en": "alone", "kr": "다만 홀로(혼자서)" },
{ "en": "along", "kr": "-을 따라" },
{ "en": "aloud", "kr": "큰 소리로" },
{ "en": "alter", "kr": "바꾸다" },
{ "en": "amaze", "kr": "깜짝 놀라게 하다" },
{ "en": "among", "kr": "-중에" },
{ "en": "amuse", "kr": "재미나게 하다" },
{ "en": "angel", "kr": "천사" },
{ "en": "anger", "kr": "성" },
{ "en": "angle", "kr": "각" },
{ "en": "annoy", "kr": "귀찮게하다" },
{ "en": "apart", "kr": "떨어져서" },
{ "en": "apple", "kr": "사과" },
{ "en": "apply", "kr": "(물건을)대다" },
{ "en": "argue", "kr": "논하다" },
{ "en": "arise", "kr": "생기다" },
{ "en": "arrow", "kr": "화살" },
{ "en": "aside", "kr": "곁에" },
{ "en": "asset", "kr": "자산" },
{ "en": "avoid", "kr": "피하다" },
{ "en": "await", "kr": "기다리다" },
{ "en": "awake", "kr": "깨우다" },
{ "en": "award", "kr": "상" },
{ "en": "aware", "kr": "알고 있는" },
{ "en": "awful", "kr": "두려운" },
{ "en": "basic", "kr": "기본의" },
{ "en": "basis", "kr": "기초" },
{ "en": "beach", "kr": "해안" },
{ "en": "beard", "kr": "턱수염" },
{ "en": "beast", "kr": "짐승" },
{ "en": "begin", "kr": "시작하다" },
{ "en": "below", "kr": "아래에" },
{ "en": "berry", "kr": "액과" },
{ "en": "bible", "kr": "성서, 성경" },
{ "en": "birth", "kr": "출생" },
{ "en": "black", "kr": "검은" },
{ "en": "blame", "kr": "책망하다" },
{ "en": "blank", "kr": "공백" },
{ "en": "blast", "kr": "돌풍" },
{ "en": "blend", "kr": "혼합하다" },
{ "en": "bless", "kr": "축복하다" },
{ "en": "blind", "kr": "눈먼" },
{ "en": "blink", "kr": "(눈을)깜빡거리다" },
{ "en": "block", "kr": "덩어리" },
{ "en": "blood", "kr": "피" },
{ "en": "bloom", "kr": "쇳덩이" },
{ "en": "board", "kr": "널빤지" },
{ "en": "boost", "kr": "뒤를 밀기" },
{ "en": "brain", "kr": "뇌" },
{ "en": "brake", "kr": "브레이크" },
{ "en": "brand", "kr": "상표" },
{ "en": "brave", "kr": "용감한" },
{ "en": "bread", "kr": "빵" },
{ "en": "break", "kr": "부수다" },
{ "en": "breed", "kr": "기르다" },
{ "en": "brick", "kr": "벽돌" },
{ "en": "bride", "kr": "신부" },
{ "en": "brief", "kr": "단시간의" },
{ "en": "bring", "kr": "가져오다" },
{ "en": "broad", "kr": "(폭이)넓은" },
{ "en": "brown", "kr": "갈색의 갈색" },
{ "en": "brush", "kr": "솔" },
{ "en": "brute", "kr": "야수 짐승같은" },
{ "en": "build", "kr": "짓다" },
{ "en": "bully", "kr": "약한 자를 못살게 구는 자" },
{ "en": "bunch", "kr": "송이" },
{ "en": "burst", "kr": "파열하다" },
{ "en": "cabin", "kr": "선실" },
{ "en": "cable", "kr": "해저전신" },
{ "en": "candy", "kr": "사탕과자" },
{ "en": "carry", "kr": "나르다" },
{ "en": "carve", "kr": "조각하다" },
{ "en": "catch", "kr": "붙잡다" },
{ "en": "cater", "kr": "음식물을 마련하다" },
{ "en": "cause", "kr": "원인" },
{ "en": "cease", "kr": "그만두다 그치다 중지" },
{ "en": "chain", "kr": "사슬" },
{ "en": "chair", "kr": "의장" },
{ "en": "chaos", "kr": "혼돈" },
{ "en": "charm", "kr": "매력" },
{ "en": "chase", "kr": "쫓다" },
{ "en": "cheap", "kr": "값싼" },
{ "en": "check", "kr": "방해" },
{ "en": "cheek", "kr": "볼" },
{ "en": "cheer", "kr": "갈채" },
{ "en": "chest", "kr": "가슴팍" },
{ "en": "chief", "kr": "우두머리" },
{ "en": "child", "kr": "아이" },
{ "en": "chill", "kr": "차가움" },
{ "en": "choir", "kr": "(교회의)성가대" },
{ "en": "civil", "kr": "시민의" },
{ "en": "claim", "kr": "요구하다" },
{ "en": "clash", "kr": "충돌하다" },
{ "en": "class", "kr": "계급" },
{ "en": "clean", "kr": "청결한" },
{ "en": "clear", "kr": "맑은" },
{ "en": "clerk", "kr": "서기" },
{ "en": "cliff", "kr": "절벽" },
{ "en": "climb", "kr": "기어 오르다" },
{ "en": "cling", "kr": "밀착하다" },
{ "en": "clock", "kr": "시계" },
{ "en": "close", "kr": "닫다" },
{ "en": "cloth", "kr": "천" },
{ "en": "cloud", "kr": "구름" },
{ "en": "coach", "kr": "역마차" },
{ "en": "coast", "kr": "연안" },
{ "en": "color", "kr": "착색하다" },
{ "en": "couch", "kr": "침대" },
{ "en": "cough", "kr": "기침 기침을 하다 기침을 하여 -을 뱉어내다" },
{ "en": "could", "kr": "aucan의 과거" },
{ "en": "count", "kr": "계산" },
{ "en": "cover", "kr": "덮다" },
{ "en": "crack", "kr": "찰싹 소리내다 금가다 날카로운소리" },
{ "en": "craft", "kr": "솜씨" },
{ "en": "crash", "kr": "도산" },
{ "en": "crawl", "kr": "네발로 기다" },
{ "en": "crazy", "kr": "미친" },
{ "en": "creek", "kr": "시내" },
{ "en": "creep", "kr": "기다" },
{ "en": "crime", "kr": "범죄" },
{ "en": "crisp", "kr": "파삭파삭한" },
{ "en": "cross", "kr": "십자형" },
{ "en": "crowd", "kr": "군중" },
{ "en": "crown", "kr": "왕관" },
{ "en": "cruel", "kr": "잔인한" },
{ "en": "crush", "kr": "눌러 부수다" },
{ "en": "curry", "kr": "카레요리 카레로 맛을 내다" },
{ "en": "curse", "kr": "저주" },
{ "en": "curve", "kr": "곡선" },
{ "en": "cycle", "kr": "순환" },
{ "en": "dairy", "kr": "낙농장" },
{ "en": "dance", "kr": "댄스" },
{ "en": "death", "kr": "죽음" },
{ "en": "decay", "kr": "쇠퇴하다" },
{ "en": "delay", "kr": "늦추다" },
{ "en": "demon", "kr": "악마" },
{ "en": "dense", "kr": "짙은" },
{ "en": "devil", "kr": "악마" },
{ "en": "diary", "kr": "일기" },
{ "en": "dirty", "kr": "더러운" },
{ "en": "doubt", "kr": "의심" },
{ "en": "dozen", "kr": "1다스" },
{ "en": "draft", "kr": "초고" },
{ "en": "drain", "kr": "배수하다" },
{ "en": "dread", "kr": "두려워하다 두려움" },
{ "en": "dream", "kr": "꿈" },
{ "en": "drink", "kr": "마시다" },
{ "en": "drive", "kr": "운전하다" },
{ "en": "drown", "kr": "물에빠뜨리다" },
{ "en": "dwell", "kr": "거주하다" },
{ "en": "eager", "kr": "열심인" },
{ "en": "early", "kr": "이른" },
{ "en": "earth", "kr": "지구" },
{ "en": "elect", "kr": "선거하다" },
{ "en": "empty", "kr": "빈" },
{ "en": "enemy", "kr": "적" },
{ "en": "enjoy", "kr": "즐기다" },
{ "en": "enter", "kr": "들어가다" },
{ "en": "entry", "kr": "들어감" },
{ "en": "equal", "kr": "같은" },
{ "en": "erect", "kr": "똑바로 선" },
{ "en": "error", "kr": "잘못" },
{ "en": "every", "kr": "모든" },
{ "en": "exact", "kr": "정확한" },
{ "en": "exist", "kr": "존재하다" },
{ "en": "extra", "kr": "가외의" },
{ "en": "faint", "kr": "기절하다" },
{ "en": "faith", "kr": "신용" },
{ "en": "false", "kr": "거짓" },
{ "en": "fancy", "kr": "공상" },
{ "en": "fatal", "kr": "치명적인" },
{ "en": "fault", "kr": "결점" },
{ "en": "favor", "kr": "호의" },
{ "en": "ferry", "kr": "나루터" },
{ "en": "fever", "kr": "열" },
{ "en": "fiber", "kr": "섬유" },
{ "en": "field", "kr": "들" },
{ "en": "fight", "kr": "싸움" },
{ "en": "final", "kr": "최후의" },
{ "en": "flame", "kr": "불꽃" },
{ "en": "flash", "kr": "번쩍임" },
{ "en": "flesh", "kr": "살" },
{ "en": "float", "kr": "뜨다" },
{ "en": "flock", "kr": "무리" },
{ "en": "flood", "kr": "홍수" },
{ "en": "floor", "kr": "마룻바닥" },
{ "en": "fluid", "kr": "유동성의" },
{ "en": "flush", "kr": "왈칵흐르다" },
{ "en": "focus", "kr": "초점" },
{ "en": "force", "kr": "힘" },
{ "en": "forth", "kr": "앞으로" },
{ "en": "forum", "kr": "공개토론회" },
{ "en": "frame", "kr": "구조" },
{ "en": "fresh", "kr": "새로운" },
{ "en": "front", "kr": "정면" },
{ "en": "frost", "kr": "서리" },
{ "en": "frown", "kr": "눈살을 찌푸리다" },
{ "en": "fruit", "kr": "과일" },
{ "en": "genre", "kr": "유형" },
{ "en": "ghost", "kr": "유령" },
{ "en": "giant", "kr": "거인" },
{ "en": "glare", "kr": "번쩍이는 빛" },
{ "en": "glass", "kr": "유리" },
{ "en": "glory", "kr": "영광" },
{ "en": "glove", "kr": "장갑" },
{ "en": "goods", "kr": "상품" },
{ "en": "grace", "kr": "은총" },
{ "en": "grade", "kr": "등급" },
{ "en": "grain", "kr": "곡물" },
{ "en": "grand", "kr": "위대한" },
{ "en": "grant", "kr": "받아들이다" },
{ "en": "grape", "kr": "포도" },
{ "en": "grasp", "kr": "붙잡다" },
{ "en": "grass", "kr": "풀밭" },
{ "en": "grave", "kr": "무덤" },
{ "en": "great", "kr": "커다란" },
{ "en": "greed", "kr": "탐욕" },
{ "en": "green", "kr": "초록색" },
{ "en": "greet", "kr": "인사하다" },
{ "en": "grief", "kr": "심한 슬픔(deep sorrow)" },
{ "en": "gross", "kr": "총계의" },
{ "en": "group", "kr": "집단" },
{ "en": "guess", "kr": "추측(짐작)하다" },
{ "en": "guest", "kr": "손님" },
{ "en": "guide", "kr": "이끌다" },
{ "en": "habit", "kr": "습관" },
{ "en": "happy", "kr": "행운의" },
{ "en": "harsh", "kr": "거친" },
{ "en": "haste", "kr": "급함" },
{ "en": "haunt", "kr": "자주가다" },
{ "en": "heart", "kr": "심장" },
{ "en": "heavy", "kr": "무거운" },
{ "en": "hello", "kr": "여보" },
{ "en": "hence", "kr": "그러므로" },
{ "en": "hobby", "kr": "취미" },
{ "en": "honey", "kr": "벌꿀" },
{ "en": "honor", "kr": "명예" },
{ "en": "horse", "kr": "말" },
{ "en": "house", "kr": "집" },
{ "en": "human", "kr": "인간의" },
{ "en": "humor", "kr": "유우머" },
{ "en": "hurry", "kr": "서두르다" },
{ "en": "ideal", "kr": "이상" },
{ "en": "imply", "kr": "함축하다" },
{ "en": "index", "kr": "색인" },
{ "en": "infer", "kr": "추론하다" },
{ "en": "input", "kr": "투입" },
{ "en": "irony", "kr": "반어" },
{ "en": "jeans", "kr": "청바지" },
{ "en": "joint", "kr": "이음매" },
{ "en": "judge", "kr": "재판관" },
{ "en": "knife", "kr": "나이프" },
{ "en": "knock", "kr": "치다" },
{ "en": "label", "kr": "라벨" },
{ "en": "labor", "kr": "노동" },
{ "en": "large", "kr": "큰" },
{ "en": "laugh", "kr": "(소리내어)웃다" },
{ "en": "layer", "kr": "층" },
{ "en": "learn", "kr": "배우다" },
{ "en": "lease", "kr": "임대차" },
{ "en": "leave", "kr": "남기고가다" },
{ "en": "legal", "kr": "법률상의" },
{ "en": "level", "kr": "수평의" },
{ "en": "light", "kr": "빛" },
{ "en": "limit", "kr": "한계" },
{ "en": "local", "kr": "장소의" },
{ "en": "logic", "kr": "논리학" },
{ "en": "loose", "kr": "풀어진" },
{ "en": "loyal", "kr": "충성스러운" },
{ "en": "lunch", "kr": "점심" },
{ "en": "major", "kr": "큰쪽의" },
{ "en": "marry", "kr": "결혼하다" },
{ "en": "match", "kr": "성냥" },
{ "en": "maybe", "kr": "아마" },
{ "en": "mayor", "kr": "시장" },
{ "en": "merge", "kr": "합병하다" },
{ "en": "merit", "kr": "장점" },
{ "en": "metal", "kr": "금속" },
{ "en": "might", "kr": "힘" },
{ "en": "miner", "kr": "광산업자" },
{ "en": "minor", "kr": "작은 편의" },
{ "en": "money", "kr": "금전" },
{ "en": "month", "kr": "월" },
{ "en": "moral", "kr": "도덕의" },
{ "en": "mount", "kr": "산" },
{ "en": "mouse", "kr": "새앙쥐" },
{ "en": "mouth", "kr": "입" },
{ "en": "movie", "kr": "영화" },
{ "en": "music", "kr": "음악" },
{ "en": "naive", "kr": "소박한" },
{ "en": "naked", "kr": "발가벗은" },
{ "en": "nanny", "kr": "유모" },
{ "en": "nasty", "kr": "불쾌한" },
{ "en": "never", "kr": "결코 -아니다" },
{ "en": "night", "kr": "밤" },
{ "en": "noble", "kr": "고귀한" },
{ "en": "noise", "kr": "소리" },
{ "en": "north", "kr": "북, 북 쪽, 북부" },
{ "en": "novel", "kr": "소설" },
{ "en": "nurse", "kr": "유모" },
{ "en": "occur", "kr": "일어나다" },
{ "en": "ocean", "kr": "대양" },
{ "en": "offer", "kr": "권하다" },
{ "en": "often", "kr": "자주" },
{ "en": "olive", "kr": "올리브나무" },
{ "en": "orbit", "kr": "궤도" },
{ "en": "order", "kr": "순서" },
{ "en": "organ", "kr": "(생물의)기관" },
{ "en": "other", "kr": "다른 다른 것 그렇지 않고" },
{ "en": "ought", "kr": "au해야만 하다" },
{ "en": "ounce", "kr": "삵괭이" },
{ "en": "paint", "kr": "도료" },
{ "en": "panel", "kr": "판벽널" },
{ "en": "panic", "kr": "돌연한공포" },
{ "en": "pants", "kr": "바지" },
{ "en": "paper", "kr": "종이" },
{ "en": "patch", "kr": "깁는 헝겊" },
{ "en": "pause", "kr": "중지" },
{ "en": "peace", "kr": "평화" },
{ "en": "phase", "kr": "국면" },
{ "en": "piece", "kr": "한 조각" },
{ "en": "pinch", "kr": "꼬집다" },
{ "en": "pitch", "kr": "던지다" },
{ "en": "place", "kr": "장소" },
{ "en": "plain", "kr": "분명한" },
{ "en": "plant", "kr": "실물" },
{ "en": "plate", "kr": "판" },
{ "en": "point", "kr": "점" },
{ "en": "polar", "kr": "남극의" },
{ "en": "power", "kr": "힘" },
{ "en": "press", "kr": "강제로 모집하다" },
{ "en": "price", "kr": "값, 가격, 대가, 정가" },
{ "en": "pride", "kr": "자존심" },
{ "en": "prime", "kr": "수위의, 최초의, 원시적인" },
{ "en": "print", "kr": "인쇄하다, 프린트하다" },
{ "en": "prior", "kr": "이전의, 앞의" },
{ "en": "prize", "kr": "상, 포상, 우등상, 선행상" },
{ "en": "proof", "kr": "증명" },
{ "en": "proud", "kr": "뽐내는, 자랑하는 자긍하는, 영광 으로 여기는" },
{ "en": "prove", "kr": "시험하다, 실험하다, 경험하다, 시험해 보다" },
{ "en": "punch", "kr": "주먹질, 펀치  힘, 활기" },
{ "en": "pupil", "kr": "흔히 국민학교 중학교 학생" },
{ "en": "puppy", "kr": "강아지" },
{ "en": "queen", "kr": "여왕" },
{ "en": "quick", "kr": "빠른" },
{ "en": "quiet", "kr": "조용한" },
{ "en": "quite", "kr": "아주" },
{ "en": "quote", "kr": "인용하다" },
{ "en": "raise", "kr": "올리다" },
{ "en": "rally", "kr": "규합하다" },
{ "en": "range", "kr": "줄" },
{ "en": "rapid", "kr": "빠른" },
{ "en": "reach", "kr": "도착하다" },
{ "en": "react", "kr": "반응을 나타내다" },
{ "en": "ready", "kr": "준비가 된" },
{ "en": "rebel", "kr": "반역자" },
{ "en": "refer", "kr": "조회시키다" },
{ "en": "relax", "kr": "늦추다" },
{ "en": "reply", "kr": "대답하다" },
{ "en": "right", "kr": "올바른" },
{ "en": "rival", "kr": "경쟁자 경쟁하는 경쟁하다" },
{ "en": "river", "kr": "강" },
{ "en": "roast", "kr": "불에 쬐어 굽다 불고기 구운" },
{ "en": "rough", "kr": "거친" },
{ "en": "round", "kr": "둥근 원 돌아서" },
{ "en": "route", "kr": "길" },
{ "en": "royal", "kr": "왕의" },
{ "en": "rumor", "kr": "소문" },
{ "en": "rural", "kr": "시골의" },
{ "en": "salon", "kr": "객실" },
{ "en": "scale", "kr": "비늘(모양의 것)" },
{ "en": "scare", "kr": "위협하다" },
{ "en": "scene", "kr": "장면" },
{ "en": "scold", "kr": "꾸짖다 잔소리 심한 사람" },
{ "en": "scope", "kr": "범위" },
{ "en": "score", "kr": "득점" },
{ "en": "screw", "kr": "나사" },
{ "en": "scrub", "kr": "(관목의)숲" },
{ "en": "seize", "kr": "붙잡다" },
{ "en": "sense", "kr": "감각" },
{ "en": "serve", "kr": "섬기다" },
{ "en": "shade", "kr": "그늘" },
{ "en": "shake", "kr": "흔들어 움직이다" },
{ "en": "shall", "kr": "au-하겠다" },
{ "en": "shame", "kr": "부끄럼" },
{ "en": "shape", "kr": "모양" },
{ "en": "share", "kr": "몫" },
{ "en": "sharp", "kr": "날카로운" },
{ "en": "shave", "kr": "깎다" },
{ "en": "sheep", "kr": "양" },
{ "en": "sheet", "kr": "깔천" },
{ "en": "shelf", "kr": "선반" },
{ "en": "shell", "kr": "겉껍질" },
{ "en": "shift", "kr": "옮기다" },
{ "en": "shine", "kr": "빛나다" },
{ "en": "shock", "kr": "격돌" },
{ "en": "shoot", "kr": "쏘다" },
{ "en": "shore", "kr": "물가" },
{ "en": "short", "kr": "짧은" },
{ "en": "shout", "kr": "외치다" },
{ "en": "sight", "kr": "광경" },
{ "en": "silly", "kr": "어리석은 바보" },
{ "en": "since", "kr": "-이래" },
{ "en": "skill", "kr": "숙련" },
{ "en": "skirt", "kr": "스커어트" },
{ "en": "slave", "kr": "노예 노예처럼 일하다" },
{ "en": "sleep", "kr": "잠자다" },
{ "en": "slice", "kr": "얇은조각" },
{ "en": "slide", "kr": "미끄러지다" },
{ "en": "slope", "kr": "비탈" },
{ "en": "small", "kr": "작은 작은 부분 적게" },
{ "en": "smart", "kr": "재치있는" },
{ "en": "smash", "kr": "박살내다" },
{ "en": "smell", "kr": "냄새" },
{ "en": "smile", "kr": "미소짓다 미소" },
{ "en": "smoke", "kr": "연기" },
{ "en": "snake", "kr": "뱀" },
{ "en": "sneak", "kr": "몰래 움직이다" },
{ "en": "sniff", "kr": "코를 킁킁거리다" },
{ "en": "solid", "kr": "고체의" },
{ "en": "solve", "kr": "해결하다" },
{ "en": "sorry", "kr": "가엾은" },
{ "en": "sound", "kr": "소리" },
{ "en": "south", "kr": "남쪽 남쪽의 남으로" },
{ "en": "space", "kr": "공간" },
{ "en": "spare", "kr": "여분의" },
{ "en": "spark", "kr": "불꽃" },
{ "en": "speak", "kr": "이야기하다" },
{ "en": "speed", "kr": "속도" },
{ "en": "spell", "kr": "철자하다" },
{ "en": "spend", "kr": "소비하다" },
{ "en": "spill", "kr": "엎지르다" },
{ "en": "spite", "kr": "악의" },
{ "en": "split", "kr": "쪼개다" },
{ "en": "spoil", "kr": "망쳐놓다" },
{ "en": "spoon", "kr": "숟가락" },
{ "en": "stack", "kr": "낟가리" },
{ "en": "stage", "kr": "무대" },
{ "en": "stain", "kr": "더럽히다" },
{ "en": "stamp", "kr": "도장" },
{ "en": "stand", "kr": "서다" },
{ "en": "stare", "kr": "응시하다" },
{ "en": "start", "kr": "시작하다" },
{ "en": "state", "kr": "상태" },
{ "en": "steal", "kr": "훔치다" },
{ "en": "steam", "kr": "증기" },
{ "en": "steel", "kr": "강철" },
{ "en": "steep", "kr": "가파른 -에 담그다 잠기다 담그기" },
{ "en": "stick", "kr": "나무토막" },
{ "en": "stiff", "kr": "굳은" },
{ "en": "still", "kr": "소리가 없는 아직(도)" },
{ "en": "stock", "kr": "줄기" },
{ "en": "stone", "kr": "돌" },
{ "en": "store", "kr": "가게" },
{ "en": "storm", "kr": "폭풍" },
{ "en": "story", "kr": "층" },
{ "en": "stove", "kr": "stave의 과거(분사)" },
{ "en": "straw", "kr": "짚" },
{ "en": "strip", "kr": "벗기다" },
{ "en": "study", "kr": "학문" },
{ "en": "stuff", "kr": "재료" },
{ "en": "sugar", "kr": "설탕" },
{ "en": "suite", "kr": "수행원" },
{ "en": "super", "kr": "임시고용배우" },
{ "en": "swear", "kr": "맹세하다" },
{ "en": "sweat", "kr": "땀" },
{ "en": "sweep", "kr": "청소하다" },
{ "en": "sweet", "kr": "단" },
{ "en": "swell", "kr": "부풀다" },
{ "en": "swift", "kr": "빠른" },
{ "en": "swing", "kr": "흔들리다" },
{ "en": "table", "kr": "테이블" },
{ "en": "taste", "kr": "맛" },
{ "en": "teach", "kr": "가르치다" },
{ "en": "tease", "kr": "괴롭히다" },
{ "en": "tempt", "kr": "유혹하다" },
{ "en": "tense", "kr": "시제" },
{ "en": "thank", "kr": "감사하다 감사" },
{ "en": "theme", "kr": "논제" },
{ "en": "there", "kr": "거기에" },
{ "en": "thick", "kr": "두꺼운" },
{ "en": "thief", "kr": "도둑" },
{ "en": "thing", "kr": "물건" },
{ "en": "think", "kr": "생각하다" },
{ "en": "throw", "kr": "던지다" },
{ "en": "thumb", "kr": "엄지손가락 엄지손가락으로 만지다" },
{ "en": "tiger", "kr": "호랑이" },
{ "en": "tight", "kr": "단단한" },
{ "en": "title", "kr": "표제" },
{ "en": "today", "kr": "오늘은" },
{ "en": "tooth", "kr": "이" },
{ "en": "total", "kr": "총계 전체의 합계하다" },
{ "en": "touch", "kr": "닿다" },
{ "en": "tough", "kr": "단단한" },
{ "en": "tower", "kr": "탑" },
{ "en": "toxic", "kr": "독의" },
{ "en": "trace", "kr": "발자국" },
{ "en": "trade", "kr": "매매" },
{ "en": "trail", "kr": "질질 끌다" },
{ "en": "train", "kr": "기차" },
{ "en": "treat", "kr": "대우하다" },
{ "en": "trend", "kr": "방향" },
{ "en": "trial", "kr": "시험" },
{ "en": "tribe", "kr": "종족" },
{ "en": "trick", "kr": "책략" },
{ "en": "troop", "kr": "대" },
{ "en": "trunk", "kr": "줄기" },
{ "en": "trust", "kr": "신용" },
{ "en": "truth", "kr": "진리" },
{ "en": "tutor", "kr": "가정교사" },
{ "en": "twice", "kr": "두 번" },
{ "en": "twist", "kr": "꼬이다" },
{ "en": "uncle", "kr": "아저씨" },
{ "en": "under", "kr": "-아래에" },
{ "en": "unify", "kr": "하나로 하다" },
{ "en": "union", "kr": "결합" },
{ "en": "unite", "kr": "결합하다" },
{ "en": "until", "kr": "-까지" },
{ "en": "upper", "kr": "위쪽의" },
{ "en": "upset", "kr": "뒤집어 엎다" },
{ "en": "urban", "kr": "도시의" },
{ "en": "usual", "kr": "평소의" },
{ "en": "utter", "kr": "전적인" },
{ "en": "vague", "kr": "막연한" },
{ "en": "valid", "kr": "유효한" },
{ "en": "value", "kr": "가치" },
{ "en": "verse", "kr": "시의 한 줄, 시구  일련의 시구" },
{ "en": "visit", "kr": "방문하다, …의 손님으로 묵다" },
{ "en": "vital", "kr": "생명의, 생명에 관한, 생명유지에 필요한, 살아 있는" },
{ "en": "vivid", "kr": "발랄한, 약동적인, 힘찬, 생기있는" },
{ "en": "voice", "kr": "목소리, 음성, 음성" },
{ "en": "wagon", "kr": "짐마차" },
{ "en": "waste", "kr": "낭비하다" },
{ "en": "watch", "kr": "손목시계" },
{ "en": "water", "kr": "물" },
{ "en": "weave", "kr": "짜다" },
{ "en": "weigh", "kr": "무게를 달다" },
{ "en": "weird", "kr": "불가사의한" },
{ "en": "whale", "kr": "고래" },
{ "en": "wheat", "kr": "밀" },
{ "en": "wheel", "kr": "바퀴" },
{ "en": "where", "kr": "어디에 (-하는)곳에 pr.어디 (문제의)장소" },
{ "en": "which", "kr": "어느 쪽" },
{ "en": "while", "kr": "동안 -하는 동안" },
{ "en": "white", "kr": "흰" },
{ "en": "whole", "kr": "전체의" },
{ "en": "widow", "kr": "미망인" },
{ "en": "woman", "kr": "부인" },
{ "en": "world", "kr": "세계" },
{ "en": "worry", "kr": "근심하다" },
{ "en": "worth", "kr": "가치가 있는 가치" },
{ "en": "would", "kr": "auwill의 과거" },
{ "en": "wound", "kr": "부상" },
{ "en": "wreck", "kr": "난파" },
{ "en": "write", "kr": "쓰다" },
{ "en": "wrong", "kr": "나쁜" },
{ "en": "yield", "kr": "산출하다" },
{ "en": "young", "kr": "젊은" },
{ "en": "zebra", "kr": "얼룩말" }]